name: Deployment pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm run install:pipeline
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build:pipeline
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3001
          env: MONGODB_URI=${{variables.MONGODB_URI}},port=3001
      - name: Deploy to production
        if: ${{ github.event_name == 'push' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          
#      - name: Test Success
#        uses: rjstone/discord-webhook-notify@v1
#        if: ${{ success() && github.event_name == 'push' }}
#        with:
#          severity: info
#          description: "https://fullstackphonebookpipeline.onrender.com/"
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#          text: "New version"

#      - name: Test Failure
#        uses: rjstone/discord-webhook-notify@v1
#        if: ${{ failure() && github.event_name == 'push' }}
#        with:
#          severity: error
#          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
#          text: "Build failed" 
          
          
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{!contains(join( toJson(github.event.commits.*.message) ), '#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch